### ISSUE TITLE
Cursor quitted out of the canvas zone

### ISSUE THREAD

**Issue by josemhdez** [Inevio/Texts#12]
All navigators, when I try to select a specific zone on texts but at the same time i want to keep on selecting until the page before, it doent pass the page and also it keeps selected without clicking left mouse button.

http://wz.io/f/X1rDnkrA

Thanks!

**Comment by javiergarmon** [comment]
Fixed with https://github.com/Inevio/Texts/commit/604a163fc85a9fb276e0eed7884197963e6341ea
