### ISSUE TITLE
Problems with Ctrl+V 

### ISSUE THREAD

**Issue by josemhdez** [Inevio/Texts#6]
On IE 10 and on Chrome 42.0 doesn´t work at all. On the latest version of Mozilla works, but the words doesn´t follow a pattern from the texts tool. When you try to erase them, it works but sooo slow and halfway only.

http://wz.io/f/ruJzBfP9

Thank you!

**Comment by josemhdez** [comment]
Also for pasting, right click + paste doesn´t work in any navigator

**Comment by javiergarmon** [comment]
Copy, cut and paste aren't implemented. We're working on it.

**Comment by javiergarmon** [comment]
Functionality implemented. Closed! :smile:
