### ISSUE TITLE
Save the changes? Design

### ISSUE THREAD

**Issue by josemhdez** [Inevio/Texts#7]
Only on Mozilla latest version:  When texts ask you if you want to really exit and save the changes, the icons, in my personal opinion, are too close one from another. Is it possible to put a bit more of distance between them?

![guardarcambios](https://cloud.githubusercontent.com/assets/12035376/7353244/7bd50488-ed12-11e4-90af-8015dc61b16f.PNG)

Thank You!

**Comment by javiergarmon** [comment]
The expected behaviour is this:
![screen shot 2015-04-27 at 20 59 22](https://cloud.githubusercontent.com/assets/1794673/7355165/76ed1d1c-ed20-11e4-826e-118c17618070.png)

So it seems a problem with the spanish version. Let me check it :wink:

**Comment by javiergarmon** [comment]
Improved design

![screen shot 2015-06-24 at 15 21 06](https://cloud.githubusercontent.com/assets/1794673/8330900/0497f718-1a85-11e5-8cd8-f8be818f5710.png)

Closed!
